// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	endpoint "github.com/faith/goKitAdvanced4/hello/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := mux.NewRouter()
	makeStatusHandler(m, endpoints, options["Status"])
	makeGetHandler(m, endpoints, options["Get"])
	makeValidateHandler(m, endpoints, options["Validate"])
	return m
}
